			.ORIG X3000
			
			AND R0 R0 R0
			STI R0 SR
			LD R6 STACK			;STARTS STACK AT X3000
			LDI R0 SR
			LD R1 ENINT
			ADD R0 R1 R0
			STI R0 SR
			
			LD R0 INTA
			STI R0 KINT			;STORES X1500 INTO X0180 I.E. THE SERVICE STARTING ADDRESS TO KEYB INT

START		LEA R0 LINE1
			TRAP X22
			
			JSR DELAY
			LD R0 LF
			TRAP X21
			LEA R0 LINE2
			TRAP X22
			
			JSR DELAY
			LD R0 LF
			TRAP X21
			BRnzp START
			
			TRAP X25
			

		
		
		
DELAY		ST R1 SAVER1
			LD R1 COUNT
REP			ADD R1 R1 #-1
			BRp REP
			LD R1 SAVER1
			RET
			
SR			.FILL XFE00
ENINT		.FILL X4000
COUNT		.FILL #2500
SAVER1		.BLKW 1
STACK		.FILL X3000
LF			.FILL X000A		
INTA		.FILL X1500
KINT		.FILL X0180
LINE1		.STRINGZ "ECE@UT       ECE@UT       ECE@UT       ECE@UT       ECE@UT       "
LINE2		.STRINGZ "       ECE@UT       ECE@UT       ECE@UT       ECE@UT"


			.END